<?php $wallet = Mage::helper('latipay')->getWalletData(); ?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="latipay-payment">
        <span class="latipay-payment__info"><?php echo $this->__('You will be redirected to Latipay after order confirmation.'); ?></span>
        <br/>
        <span class="latipay-payment__info"><?php echo $this->__('Latipay offers the above options to make a secure payment.'); ?></span>
        <ul class="latipay-options">
            <?php foreach($wallet as $wkey =>$wvalue){ ?>
            <li class="latipay-options-item">
            <input name="payment[latipay_method]" id="latipay-method-<?php echo strtolower($wvalue); ?>" type="radio" value="<?php echo strtolower($wvalue); ?>" <?php if($wkey == 0){echo 'checked="checked"';} ?>>
                <label for="latipay-method-<?php echo strtolower($wvalue); ?>"><?php echo $wvalue; ?></label>
            </li>
            <?php } ?>
        </ul>
    </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
